#!/bin/bash

# git clone https://github.com/js20180814/release.git
# ./push "xxx"
# git remote rm origin
# git remote add origin https://github.com/js20180814/release.git
# git push -u origin master

if [ "$1" = "remote-add" ] ;then
  git remote add origin https://github.com/js20180814/release.git
  exit 0
fi

git add --all;
git commit -am "<$1>";
git pull origin master;   
git push -u origin master;











